src/index.ts, test/fixture/nuxt.config.ts
- Having a components dir with `index.js` at root, breaks module
- Warn about not found dirs
closes #10
=> fix: properly resolve components dir name and warn about non existent dirs

README.md
Fixes line 45, changes `there` to `they`
=> docs: fix typo in components

src/index.ts, src/scan.ts, test/fixture/my-lib/components/MAwesome.js, test/fixture/my-lib/components/index.js, test/fixture/nuxt.config.ts, test/fixture/pages/index.vue, test/module.test.ts, test/unit/loader.test.ts, test/unit/tagExtractor.test.ts
Addressing #9, #11
Component libraries, not always follow same conventions. This PR allows better integration with 3rd party libraries meanwhile keeping it as easy as possible.
While preserving scanner convenience allows customizing scanned components. Extendable fields:
- filePath
- pascalName
- kebabName
- chunkName
- shortPath
- import (*)
- asyncImport (*)
- export
*: Can generate but the value is resolved after hook as it depends on `export` value
**Example:** A library using named exports per component: (BootstrapVue for instance)
```js
// Used in dirs or added by hook
{
path: path.resolve(__dirname, 'my-lib/components'),
extendComponent: _c => ({ ..._c, export: _c.pascalName })
}
```
This hook allows extending the final `components` result. Useful for additional post-proccessing …
=> feat: advanced library integration

README.md, src/index.ts
- Allow using `components: []` inside `nuxt.config`
- Only enabled default `~/components` if `components` key exists in `nuxt.config` with a truethy value
- Simplify docs [rendered version](https://github.com/nuxt/components/blob/feat/components-array/README.md)
=> feat: components array and simplify usage

README.md, src/index.ts, test/fixture/nuxt.config.ts, test/unit/scanner.test.ts
Simplify default pattern generation mostly useful for folder format (#29)
Related PR: #30
=> feat: support dir.extensions

README.md
Making it clear that regardless of nuxt version, the `components: true` option must be set.
Preventing: https://github.com/nuxt/components/issues/38
=> docs: make `components: true` requirement clear

src/index.ts, src/scan.ts
Fulfill requirements of #18:
- Disable webpack dependency on dirs with `global: true`
- Completely disable webpack loader if all dirs are global
- Support `global: 'dev'` option
nuxt.config:
```js
export default {
components: [ { path: '~/components', global: 'dev' } ]
}
```
=> fix: disable loader for global dirs

src/index.ts
Add `*.stories.js` to ignore list.
Currently, the Component module detects Storybook files as components.  
See https://github.com/nuxt-community/storybook/issues/23
=> feat: ignore storybook stories

package.json, yarn.lock
Related to https://github.com/nuxt/create-nuxt-app/issues/642
NPM 7 will automatically installing peer dependencies, so webpack@5 may be hoisted to root node module, but this pacakge doesn't have peer dependency for webpack@4, so it will wrongly require webpack@5
=> fix(npm7): component may require wrong webpack version

README.md, src/index.ts, test/fixture/nuxt.config.ts, yarn.lock
This feature add the `components/global/` directory to the list with `global: true` option.
This has been used by @nuxt/content for a while and I believe it is relevant to add it by default into @nuxt/components.
See [updated documentation](https://github.com/nuxt/components/blob/6fa5883242a903466b65ea838d72c854d5dd05bb/README.md#dynamic-components)
=> feat: add components/global/ directory

src/index.ts
Improve stories ignore pattern to ignore `ts`, `tsx` and `jsx` files.  
Having these files in the project will lead to invalid js syntax error. (https://github.com/nuxt-community/storybook/issues/222#issuecomment-769788773)
=> fix(ignore): ignore typescript stories

README.md, src/index.ts, src/loader.ts, src/types.ts, templates/components/plugin.js, test/fixture/components/functional/FunctionalChild.vue, test/fixture/pages/pug.vue
With #43, we added support for `global: true` and introduced an  auto generated plugin that instead of loader strategy, globally registers components with async chunks. This option was disabled for 1-production to reduce network requests/size and allow webpack [smartly chunking](https://webpack.js.org/plugins/split-chunks-plugin/) per page and for 2-development to make behavior consistent with production and being aware if a component cannot work with loader.
It is proved that loader approach is not good for DX both for dev performance and limitations for detecting components. On the other hands without loader prod build is not optimized.
Approach of this PR is to globally register all components (async loaded) but when loader detects component usage per page, directly imports them (vue …
=> feat: components always available globally (hybrid loader)

src/index.ts
As sugested in #108 I wasn't sure whether this is case-insensitive, so I assumed it isn't and added `{m,M}`. BTW, would it be possible to bump the Nuxt version? This package has some interesting bugfixes which I'd love to see as a dependency update included in Nuxt.
resolves #108
=> feat: included pattern to ignore mixins

src/scan.ts, test/fixture/components/global/Deep/Nested/MyComponent.vue, test/unit/scanner.test.ts
If components were in multilevel nested folders the component name was invalid:
before:
`components/Deep/Nested/MyComponent` ->  `Deep/NestedMyComponent`
after:
`components/Deep/Nested/MyComponent` -> `DeepNestedMyComponent`
=> fix: allow components to be in multilevel nested folders

src/index.ts, src/scan.ts, templates/components/readme.md
Sometimes it is hard to inspect name of components are which auto-registered. This small change generates a readme file in `.nuxt` directory and console log to inform users about discovered components.
This is initial attempt to improve DX of discovered components. In next steps we shall use a web UI to provide catalog and playground for components.
Example CLI output:
```
ℹ Auto discovered components: .nuxt/components/readme.md 
```
Example md:
This is an auto generated list of components discovered by [nuxt/components](https://github.com/nuxt/components)
You can directly use them by name without need to import.
**Tip:** If component is conditionally rendered with `v-if` and is big, it is better to use `Lazy` or `lazy-` prefix to lazy load them.
- `<Big>` | `<big>` …
=> chore(dx): generate list of discovered components

package.json, src/scan.ts, test/fixture/components/ui/notification/NotificationWrapper.vue, test/unit/scanner.test.ts, yarn.lock
- Replace lodash / pascal utils with [nuxt-contrib/scule](https://github.com/nuxt-contrib/scule)
- Handles mixed cases, different separators and case-aware splitting
- Change prefix checking algorithm to handle new case: `ui/Notification/NotificationWrapper` (*)
New duplicate removal algorthm:
- Create an empty array arr
- Do case aware splitting for both fileName and it's nested path (prefix)
- While first item of prefix is not same as first item of file name (case insensitive)
- shift from prefix and push to arr
- Add rest of fileName parts
- Join arr and file name parts with PascalCase convention 
Example: `A-B/C/D/CDE.vue` => `<ABCDE>`
Also fixes nuxt/nuxt.js#8836
=> fix(scan): avoid duplicate prefix

src/scan.ts, templates/components/index.js, test/unit/loader.test.ts, test/unit/matcher.test.ts, test/unit/scanner.test.ts
- Remove generation of extra `Lazy` components (we register them globally and loader does not needs them)
- Split `prefix` dir option to avoid duplicate
=> fix: improve scanner

package.json, yarn.lock
* note both #187 and #188 preceded this PR - would recommend merging one of them but opened this to document that the new syntax requires upgraded version of `siroc`
https://nodejs.org/api/packages.html#packages_subpath_folder_mappings
=> chore: fix deprecated exports syntax

package.json, src/index.ts
Nuxt has the `this.options.build.quiet` variable to decide if console output should happen. It sets `consola.level` depending on this variable.
`@nuxt/components` should also use `consola` so that the output is muted correctly. Currently, `@nuxt/components` still outputs to the console if Nuxt is built via the API.
I added `consola` as a peer dependency so that it does not install its own version.
It's actually a bit hard to test this because `@nuxt/components` is directly integrated into Nuxt.
=> fix: use consola so that this.options.build.quiet is taken into account

README.md, src/scan.ts, src/types.ts, templates/components/plugin.js
This PR is to support #71 in some way.
I just read through the code of this module once, so I may not be misunderstanding the implementation and making mistakes in approach. But, still, I will submit this PR with _WIP_ in the title, so that everyone can point them out and/or have a discussion on my implementation.
---
According to [Webpack's documentation](https://webpack.js.org/api/module-methods/#magic-comments), there are 6 kinds of magic comments supported by Webpack 4+, and they can be combined. 
- `webpackInclude`
- `webpackExclude`
- `webpackChunkName`
- `webpackMode`
- `webpackPrefetch`
- `webpackPreload`
In the context of component importing, I think it would be enough to support only `preferch` and `preload` (at least to resolve #71).
---
The author of the issue wants to set …
=> feat: support webpack magic comments

src/types.ts
Resolves #134.
Just in case, I ran `yarn run test` in my local and of course all the tests passed.
=> feat(types): export hook types
